### ISSUE TITLE
Provide an option to read Host-IP mapping from file

### ISSUE THREAD

**Issue by devenbansod** [devenbansod/pcap_to_ditg#1]
Currently the Host - IP relations are hard-coded. 
We should provide a way to make it as an user input.

**Comment by prabodh1194** [comment]
Yeah. What is that hard-coding? I'll have to read through and figure out if something can be done,

**Comment by devenbansod** [comment]
See this section in README:

> * The format of ``mapper_file`` is as follows:
>
> 
>        Host,Start_row,End_row,Number
>        h1,1734,1902,169
>        h2,1528,1733,206
>        .
>        .
>        .

**Comment by devenbansod** [comment]
This is where user defines the mapping between the original IPs (from the dump) and the Hosts in **his/her** physical topology. 

Now, see this code: https://github.com/devenbansod/pcap_to_ditg/blob/master/pcap_to_ditg/pcap_to_ditg.py#L117
which hardcodes the IPs for the hosts in his/her topology

**Comment by devenbansod** [comment]
We have to add a better interface where user can specify the mapping (because mapping is required for sure).

**Comment by prabodh1194** [comment]
and those rows are from the pcap file?

**Comment by devenbansod** [comment]
No, these are the row numbers for the `list_file` (See README again).

**Comment by prabodh1194** [comment]
oh. makes sense. thanks.

**Comment by prabodh1194** [comment]
h1,1734,1902,169
means, look at IPs in rows 1734-1902 of the list file and map them to that of h1?

**Comment by prabodh1194** [comment]
We can have another file some type of hosts file and that can be loaded in memory in a dict and the `__getIpForHost()` method can just lookup that dict and return appropriate IP, or the `mapper_file`, can carry another field called IP address, even better.

**Comment by devenbansod** [comment]
Yeah. That would be great. 
Could you go ahead and submit a PR for that ?

**Comment by prabodh1194** [comment]
close it?

**Comment by devenbansod** [comment]
Yeah. 
From the next PR, include a `Fix #1` in the commit message to auto-close the issues when the commit is merged to master.

**Comment by devenbansod** [comment]
Closed with #3

**Comment by prabodh1194** [comment]
I was wondering why didn't it autoclose, i thought reference will do it. My github is rusty.
