### ISSUE TITLE
run.py error

### ISSUE THREAD

**Issue by ghalwash** [devenbansod/pcap_to_ditg#4]
Hi Deven,
I am trying to use your pcap_to_ditg project.  I am using ubuntu 16.04 and python 2.7.12. I followed these steps with and without step 2&3.

 1. Downloaded the latest release
 2. run python setup.py build
 3. run python setup.py install
 4. touch list_file
 5. python run.py -p pcap_file.pcap mapper_file list_file > list_file
(I have all inputs as empty files)

 I am getting the following error whether or not I considered steps 2 & 3

 Traceback (most recent call last):
   File "run.py", line 51, in <module>
     options
TypeError: 'module' object is not callable

thanks

**Comment by devenbansod** [comment]
Hi @ghalwash did you try the steps I suggested in our email conversation? Did those help?

```
1. Do `pip install pcap_to_ditg`
2. Then download this file at
https://raw.githubusercontent.com/devenbansod/pcap_to_ditg/master/examples/run.py

3. Run as: ` python run.py pcap_file mapper_file list_file -p`
(assuming you have all those input files)
```

**Comment by ghalwash** [comment]
Yes it helped 
thank you so much
